name: Android build

on:
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        with:
          cache-disabled: true
          sdk-version: 35
          build-tools-version: 35.0.0

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Clear Gradle Cache
        run: rm -rf $HOME/.gradle/caches/

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Install root dependencies
        run: yarn --frozen-lockfile

      - name: Install root dependencies
        run: yarn --frozen-lockfile
        working-directory: example

      - name: Write local.properties
        run: echo >> android/local.properties && echo MAPS_API_KEY=your_api_key_here >> android/secrets.properties
        working-directory: example

      - name: Build Android
        run: cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug
        working-directory: example
