name: iOS frameworks build

on:
  pull_request:

jobs:
  build-ios-frameworks:
    runs-on: macos-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
          working-directory: packages/example

      - name: Install dependencies
        run: yarn --cwd packages/example --frozen-lockfile

      - name: Install pods
        run: RCT_NEW_ARCH_ENABLED=1 NO_FLIPPER=1 USE_FRAMEWORKS=static bundle exec pod install
        working-directory: packages/example/ios

      - name: Write Secrets.xcconfig
        run: echo MAPS_API_KEY=your_api_key_here >> packages/example/ios/Secrets.xcconfig

      - name: Build iOS
        run: xcodebuild -workspace packages/example/ios/rnmshowcase.xcworkspace -scheme rnmshowcase -configuration Debug -sdk iphonesimulator
